## Challenge 2: Sets

There are a lot to learn about Python Sets and the information presented in the lesson is limited due to its length. To learn Python Sets in depth you are strongly encouraged to review the W3Schools tutorial on [Python Sets Examples and Methods](https://www.w3schools.com/python/python_sets.asp) before you work on this lab. Some difficult questions in this lab have their solutions in the W3Schools tutorial.

#### First, import the Python `random` libary

In [3]:
import random

#### 1 - In the cell below, create a list named `sample_list_1` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* Each value in the list is unique.

Print `sample_list_1` to review its values

*Hint: use `random.sample` ([reference](https://docs.python.org/3/library/random.html#random.sample)).*

In [4]:
# Your code here


numbers = list(range(101))
length = 80

sample_list_1 = random.sample(numbers, length)
print(sample_list_1)

[76, 68, 84, 66, 44, 16, 54, 13, 81, 91, 56, 39, 98, 24, 31, 55, 26, 23, 95, 3, 41, 35, 0, 92, 9, 17, 8, 67, 61, 94, 78, 1, 12, 25, 36, 85, 15, 65, 32, 100, 45, 21, 30, 75, 5, 29, 33, 48, 70, 50, 96, 11, 60, 82, 58, 47, 14, 49, 63, 2, 38, 28, 42, 22, 46, 18, 71, 80, 74, 7, 57, 93, 20, 69, 77, 73, 37, 52, 6, 64]

#### 2 - Convert `sample_list_1` to a set called `set1`. Print the length of the set. Is its length still 80?

In [5]:
# Your code here
set1=set(sample_list_1)
print(set1)
print ("The length of set_1 is: ", len(set1))

{0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 54, 55, 56, 57, 58, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 73, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 91, 92, 93, 94, 95, 96, 98, 100}
The length of set_1 is:  80

#### 3 - Create another list named `sample_list_2` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* The values in the list don't have to be unique.

*Hint: Use a FOR loop.*

In [6]:
sample_list_2 = []

for numbers in range(80):
    random_value = random.randint(0, 100)
    sample_list_2.append(random_value)
print(sample_list_2)

[15, 86, 55, 84, 31, 94, 53, 22, 88, 57, 96, 88, 87, 36, 1, 33, 41, 90, 72, 47, 81, 52, 2, 17, 40, 22, 73, 36, 61, 79, 65, 36, 96, 81, 77, 50, 12, 15, 85, 52, 36, 41, 71, 29, 18, 41, 39, 25, 26, 93, 92, 19, 94, 41, 17, 37, 83, 76, 94, 99, 53, 21, 54, 69, 71, 52, 37, 26, 33, 24, 12, 82, 23, 73, 50, 10, 72, 50, 20, 32]

#### 4 - Convert `sample_list_2` to a set called `set2`. Print the length of the set. Is its length still 80?

In [7]:
set2= set(sample_list_2)
print(set2)
len(set2)

{1, 2, 10, 12, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 29, 31, 32, 33, 36, 37, 39, 40, 41, 47, 50, 52, 53, 54, 55, 57, 61, 65, 69, 71, 72, 73, 76, 77, 79, 81, 82, 83, 84, 85, 86, 87, 88, 90, 92, 93, 94, 96, 99}

54

#### 5 - Identify the elements present in `set1` but not in `set2`. Assign the elements to a new set named `set3`.

In [8]:
# Your code here
set3 =set()

for elements1 in set1:
  if elements1 not in set2:
    (set3.add(elements1))
print(set3)

{0, 3, 5, 6, 7, 8, 9, 11, 13, 14, 16, 28, 30, 35, 38, 42, 44, 45, 46, 48, 49, 56, 58, 60, 63, 64, 66, 67, 68, 70, 74, 75, 78, 80, 91, 95, 98, 100}

#### 6 - Identify the elements present in `set2` but not in `set1`. Assign the elements to a new set named `set4`.

In [9]:
# Your code here
set4 =set()

for elements2 in set2:
  if elements2 not in set1:
    set4.add(elements2)
print (set4)

{99, 40, 72, 10, 79, 19, 83, 53, 86, 87, 88, 90}

#### 7 - Now Identify the elements shared between `set1` and `set2`. Assign the elements to a new set named `set5`.

In [10]:
# Your code here
set5= set1.intersection(set2)
print(set5)

{1, 2, 12, 15, 17, 18, 20, 21, 22, 23, 24, 25, 26, 29, 31, 32, 33, 36, 37, 39, 41, 47, 50, 52, 54, 55, 57, 61, 65, 69, 71, 73, 76, 77, 81, 82, 84, 85, 92, 93, 94, 96}

#### 8 - Create an empty set called `set6`.

In [11]:
# Your code here
set6=set()

#### 9 - Add `set3` and `set5` to `set6` using the Python Set `update` method.

In [12]:
# Your code here
set6.update(set3,set5)
print(set6)

{0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 54, 55, 56, 57, 58, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 73, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 91, 92, 93, 94, 95, 96, 98, 100}

#### 10 - Check if `set1` and `set6` are equal.

In [13]:
# Your code here
set1==set6

True

#### 11 - Check if `set1` contains `set2` using the Python Set `issubset` method. Then check if `set1` contains `set3`.*

In [14]:
# Your code here
set1.issubset(set2)

False

In [15]:
set1.issubset(set3)

False

#### 12 -Using the Python Set `union` method, aggregate `set3`, `set4`, and `set5`. Then aggregate `set1` and `set2`.

#### Check if the aggregated values are equal.

In [16]:
# Your code here
set_agregate_1 = set3.union(set4,set5)
set_agregate_2 =set1.union(set2)

set_agregate_1== set_agregate_2

True

#### 13 -Using the `pop` method, remove the first element from `set1`.

In [17]:
# Your code here
print(set1)
set1.pop()

{0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 54, 55, 56, 57, 58, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 73, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 91, 92, 93, 94, 95, 96, 98, 100}

0

#### 14 -Remove every element in the following list from `set1` if they are present in the set. Print the remaining elements.

```
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
```

In [19]:
# Your code here

list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
for elements in list_to_remove:
  if elements in set1:
    set1.remove (elements)
print(set1)

{2, 3, 5, 6, 7, 8, 12, 13, 14, 15, 16, 17, 18, 20, 22, 23, 24, 25, 26, 28, 30, 32, 33, 35, 36, 37, 38, 42, 44, 45, 46, 47, 48, 50, 52, 54, 55, 56, 57, 58, 60, 63, 64, 65, 66, 67, 68, 70, 73, 74, 75, 76, 77, 78, 80, 82, 84, 85, 92, 93, 94, 95, 96, 98, 100}

#### 15 -The objective of this lab is to provide you a overview of manipulating sets in Python and how they can be integrated within a real usecase
#### For the exercises below it's strongly advised to quickly check this link: https://docs.python.org/2/library/sets.html#sets.Set
#### Imagine you need to create the grocery list for your family! Below you will see a list of items each family member wants. There will be repetitions because this family has the habbit of each time they notice something is missing to write it down. The problem is that they don't really talk to each other and therefore some items in the list are repeated. With the collection of questions below you will see how they solve repetion and create a grocery list with unique elements.

In [20]:
father_list = ['garlic', 'watermelon', 'toilet paper', 'yogurt', 'onions', 'gums', 'flour', 'cucumber', 'watermelon', 'yogurt', 'garlic']

mother_list = []

Jo_list = ['blueberries', 'sugar', 'watermelon', 'gums', 'tomatoes', 'yogurt', 'juice', 'milk', 'onions', 'garlic', 'cucumber', 'sugar', 'blueberries', 'gums', 'yogurt']

Carlos_list = ['tomatoes', 'water', 'onions', 'blueberries', 'garlic', 'flour', 'cherries', 'tomatoes', 'onions', 'water', 'tomatoes', 'toilet paper']

Mattia_list = []

#### 15.1- As you can see there are items repeated in each list. Creat a sequence of iterable elements with dintinct items that each family member wants. You can do it in two different ways. Assign each one (set) to a variable with the name of the family member (ex: father_set).

In [22]:
# Your code here
father_set= set (father_list)
Jo_set= set(Jo_list)
Carlos_set= set(Carlos_list)
mother_set= set(mother_list)
Mattia_set= set(Mattia_list)

#### 15.2- Q: Mattia wants the same items that his brother Carlos and his sister Jo but doesn't want anything they both want.

##### Hint: check out the documentation for `x.symmetric_difference(y)`.

In [24]:
# Your code here
Mattia_set= Carlos_set.symmetric_difference(Jo_set)
print (Mattia_set)

{'cherries', 'milk', 'water', 'gums', 'juice', 'watermelon', 'sugar', 'cucumber', 'yogurt', 'flour', 'toilet paper'}

#### 15.3- The line of code below  will  generate a list of random elements from a collection of items, with replacement. Run it and from it create a sequence of unique elements and assign it to the variable mother.

In [25]:
import random
items = ['milk', 'water', 'chocolate', 'blueberries', 'shampoo', 'flour', 'bread', 'sugar', 'watermelon', 'vinegar', 'tomatoes', 'yogurt', 'juice', 'gums', 'onions', 'garlic', 'cucumber', 'mushrooms', 'toilet paper', 'oranges', 'deodorant', 'cherries']

mother_list = random.choices(items,k = 10) # https://docs.python.org/3/library/random.html

print(mother_list)

['chocolate', 'juice', 'cucumber', 'garlic', 'juice', 'cherries', 'cucumber', 'garlic', 'bread', 'bread']

In [ ]:
# Your code here

#### 15.4- Before leaving the house to the grocery store the father found a lot of toilet paper, so the mother decided to remove it from the items needed to be bought. Use the `.discard()` method to remove from each set created before the 'toilet paper'.

#### Hint: Try to first create a list contaning the variables of each set created before, then loop through them and remove the unecessary item.

##### Note: The`.discard()` method will remove and update the set without the need of reassignment.

In [56]:
# Your code here
father_set.discard ('toilet paper')
Jo_set.discard ('toilet paper')
Carlos_set.discard ('toilet paper')
mother_set.discard ('toilet paper')
Mattia_set.discard ('toilet paper')

items_list=[father_set,Jo_set ,Carlos_set  , mother_set, Mattia_set ]

items_needed = set()

for items in items_list:
  items_needed.update(items)

  print (items_needed)

{'gums', 'onions', 'watermelon', 'cucumber', 'yogurt', 'garlic', 'flour'}
{'milk', 'onions', 'garlic', 'blueberries', 'gums', 'juice', 'watermelon', 'tomatoes', 'sugar', 'cucumber', 'yogurt', 'flour'}
{'milk', 'water', 'onions', 'garlic', 'blueberries', 'cherries', 'gums', 'juice', 'watermelon', 'tomatoes', 'sugar', 'cucumber', 'yogurt', 'flour'}
{'milk', 'water', 'onions', 'garlic', 'blueberries', 'cherries', 'gums', 'juice', 'watermelon', 'tomatoes', 'sugar', 'cucumber', 'yogurt', 'flour'}
{'milk', 'water', 'onions', 'garlic', 'blueberries', 'cherries', 'gums', 'juice', 'watermelon', 'tomatoes', 'sugar', 'cucumber', 'yogurt', 'flour'}

#### 15.5- Create a set with all the groceries needed to be bought for the house (no repetitions).

In [82]:
# Your code here
items_needed_set= set (items_needed)
print (items_needed_set)

{'blueberries', 'milk', 'water', 'cherries', 'gums', 'juice', 'watermelon', 'tomatoes', 'sugar', 'onions', 'garlic', 'cucumber', 'yogurt', 'flour'}

#### 15.6- The Father said that he could only buy five items this time. So he decided to arbitraly pick wich ones to buy this time.

##### Hint: use the `.pop()` method.

In [83]:
# Your code here

random_items_set=set()

for items in range(5):
  if items_needed_set:
    random_items=items_needed_set.pop()
    random_items_set.add (random_items)

print (random_items_set)

{'blueberries', 'milk', 'water', 'gums', 'cherries'}